// Auto-generated by gen-routes.ts
import duckduckgo from "./duckduckgo.js";
import giphy from "./giphy.js";
import google from "./google.js";
import klipy from "./klipy.js";
import tenor from "./tenor.js";
import youtube from "./youtube.js";

export default [duckduckgo, giphy, google, klipy, tenor, youtube] as any[];
