// Auto-generated by gen-routes.ts
import youtube from "./youtube.js";
import tenor from "./tenor.js";
import giphy from "./giphy.js";
import klipy from "./klipy.js";
import google from "./google.js";
import duckduckgo from "./duckduckgo.js";

export default [youtube, tenor, giphy, klipy, google, duckduckgo] as any[];
