export const DISCORD_FLAGS: Record<number, string> = {
	0: "Discord Staff",
	1: "Partnered Server Owner",
	2: "HypeSquad Events",
	3: "Bug Hunter Level 1",
	6: "HypeSquad Bravery",
	7: "HypeSquad Brilliance",
	8: "HypeSquad Balance",
	9: "Early Nitro Supporter",
	10: "Team User",
	12: "System",
	14: "Bug Hunter Level 2",
	16: "Verified Bot",
	17: "Early Verified Bot Developer",
	18: "Moderator Programs Alumni",
	19: "Bot HTTP Interactions",
	22: "Active Developer",
};

export const DISCORD_APPLICATION_FLAGS: Record<number, string> = {
	1: "EMBEDDED_RELEASED",
	2: "MANAGED_EMOJI",
	3: "EMBEDDED_IAP",
	4: "GROUP_DM_CREATE",
	6: "APPLICATION_AUTO_MODERATION_RULE_CREATE_BADGE",
	11: "RPC_HAS_CONNECTED",
	12: "GATEWAY_PRESENCE",
	13: "GATEWAY_PRESENCE_LIMITED",
	14: "GATEWAY_GUILD_MEMBERS",
	15: "GATEWAY_GUILD_MEMBERS_LIMITED",
	16: "VERIFICATION_PENDING_GUILD_LIMIT",
	17: "EMBEDDED",
	18: "GATEWAY_MESSAGE_CONTENT",
	19: "GATEWAY_MESSAGE_CONTENT_LIMITED",
	20: "EMBEDDED_FIRST_PARTY",
	23: "APPLICATION_COMMAND_BADGE",
};

export const DISCORD_APPLICATION_INTEGRATION_TYPES: Record<number, string> = {
	0: "GUILD_INSTALL",
	1: "USER_INSTALL",
};

export function resolveFlags(flags: number | null | undefined): string[] {
	if (!flags) return [];
	const badges: string[] = [];
	for (const [bit, name] of Object.entries(DISCORD_FLAGS)) {
		if (flags & (1 << Number(bit))) {
			badges.push(name);
		}
	}
	return badges;
}

export function resolveApplicationFlags(flags: string | number | null | undefined): string[] {
	if (flags === undefined || flags === null || flags === "") return [];

	let value: bigint;
	try {
		value = BigInt(String(flags));
	} catch {
		return [];
	}

	const resolved: string[] = [];
	for (let bit = 0; bit < 64; bit++) {
		if ((value & (1n << BigInt(bit))) !== 0n) resolved.push(DISCORD_APPLICATION_FLAGS[bit] || `UNKNOWN_${bit}`);
	}

	return resolved;
}

export const DISCORD_PERMISSIONS: Record<string, bigint> = {
	"Create Instant Invite": 1n << 0n,
	"Kick Members": 1n << 1n,
	"Ban Members": 1n << 2n,
	Administrator: 1n << 3n,
	"Manage Channels": 1n << 4n,
	"Manage Guild": 1n << 5n,
	"Add Reactions": 1n << 6n,
	"View Audit Log": 1n << 7n,
	"Priority Speaker": 1n << 8n,
	Stream: 1n << 9n,
	"View Channel": 1n << 10n,
	"Send Messages": 1n << 11n,
	"Send TTS Messages": 1n << 12n,
	"Manage Messages": 1n << 13n,
	"Embed Links": 1n << 14n,
	"Attach Files": 1n << 15n,
	"Read Message History": 1n << 16n,
	"Mention Everyone": 1n << 17n,
	"Use External Emojis": 1n << 18n,
	"View Guild Insights": 1n << 19n,
	Connect: 1n << 20n,
	Speak: 1n << 21n,
	"Mute Members": 1n << 22n,
	"Deafen Members": 1n << 23n,
	"Move Members": 1n << 24n,
	"Use VAD": 1n << 25n,
	"Change Nickname": 1n << 26n,
	"Manage Nicknames": 1n << 27n,
	"Manage Roles": 1n << 28n,
	"Manage Webhooks": 1n << 29n,
	"Manage Guild Expressions": 1n << 30n,
	"Use Application Commands": 1n << 31n,
	"Request to Speak": 1n << 32n,
	"Manage Events": 1n << 33n,
	"Manage Threads": 1n << 34n,
	"Create Public Threads": 1n << 35n,
	"Create Private Threads": 1n << 36n,
	"Use External Stickers": 1n << 37n,
	"Send Messages in Threads": 1n << 38n,
	"Use Embedded Activities": 1n << 39n,
	"Moderate Members": 1n << 40n,
	"View Creator Monetization Analytics": 1n << 41n,
	"Use Soundboard": 1n << 42n,
	"Create Guild Expressions": 1n << 43n,
	"Create Events": 1n << 44n,
	"Use External Sounds": 1n << 45n,
	"Send Voice Messages": 1n << 46n,
	"Use Clyde AI": 1n << 47n,
	"Set Voice Channel Status": 1n << 48n,
	"Send Polls": 1n << 49n,
	"Use External Apps": 1n << 50n,
	"Pin Messages": 1n << 51n,
	"Bypass Slowmode": 1n << 52n,
};

export const PERMISSION_KEYS: Record<string, bigint> = {
	addreactions: 1n << 6n,
	admin: 1n << 3n,
	attachfiles: 1n << 15n,
	ban: 1n << 2n,
	changenicknames: 1n << 26n,
	connect: 1n << 20n,
	createinstantinvite: 1n << 0n,
	createprivatethreads: 1n << 36n,
	createpublicthreads: 1n << 35n,
	embedlinks: 1n << 14n,
	externalemojis: 1n << 18n,
	externalstickers: 1n << 37n,
	kick: 1n << 1n,
	managechannels: 1n << 4n,
	manageemojis: 1n << 30n,
	manageevents: 1n << 33n,
	managemessages: 1n << 13n,
	managenicknames: 1n << 27n,
	manageroles: 1n << 28n,
	manageserver: 1n << 5n,
	managethreads: 1n << 34n,
	managewebhooks: 1n << 29n,
	mentioneveryone: 1n << 17n,
	moderatemembers: 1n << 40n,
	movemembers: 1n << 24n,
	priorityspeaker: 1n << 8n,
	readmessagehistory: 1n << 16n,
	readmessages: 1n << 10n,
	requesttospeak: 1n << 32n,
	sendmessages: 1n << 11n,
	sendmessagesinthreads: 1n << 38n,
	sendvoicemessages: 1n << 46n,
	setvoicechannelstatus: 1n << 48n,
	slashcommands: 1n << 31n,
	speak: 1n << 21n,
	stream: 1n << 9n,
	tts: 1n << 12n,
	bypassslowmode: 1n << 52n,
	createevents: 1n << 44n,
	pinmessages: 1n << 51n,
	useclydeai: 1n << 47n,
	useexternalapps: 1n << 50n,
	userexternalsounds: 1n << 45n,
	usesoundboard: 1n << 42n,
	usevad: 1n << 25n,
	viewauditlog: 1n << 7n,
	viewguildinsights: 1n << 19n,
	voicedeafen: 1n << 23n,
	voicemute: 1n << 22n,
};

export const DISCORD_CHANNEL_TYPES: Record<number, string> = {
	0: "text",
	2: "voice",
	4: "category",
	5: "announcement",
	10: "announcement_thread",
	11: "public_thread",
	12: "private_thread",
	13: "stage",
	14: "directory",
	15: "forum",
	16: "media",
};

export const DISCORD_STICKER_MAX_BYTES = 512 * 1024;
export const DISCORD_STICKER_MAX_CONVERT_INPUT_BYTES = 8 * 1024 * 1024;
export const DISCORD_STICKER_MIME_TO_EXT: Record<string, string> = {
	"image/png": "png",
	"image/apng": "apng",
	"image/gif": "gif",
	"application/json": "json",
};
export const DISCORD_STICKER_CONVERT_MIME_TO_PNG = new Set(["image/jpeg", "image/jpg", "image/pjpeg", "image/webp", "image/x-webp"]);
export const DISCORD_STICKER_CONVERT_EXT_TO_PNG = new Set(["jpg", "jpeg", "jpe", "jfif", "webp"]);
export const DISCORD_STICKER_EXT_TO_MIME: Record<string, string> = {
	png: "image/png",
	apng: "image/png",
	gif: "image/gif",
	json: "application/json",
};

export const DISCORD_AUTOMOD_TRIGGER_TYPES: Record<string, number> = {
	KEYWORD: 1,
	SPAM: 3,
	KEYWORD_PRESET: 4,
	MENTION_SPAM: 5,
	MEMBER_PROFILE: 6,
};

export const DISCORD_AUTOMOD_EVENT_TYPES: Record<string, number> = {
	MESSAGE_SEND: 1,
	GUILD_MEMBER_JOIN_OR_UPDATE: 2,
};

export const DISCORD_AUTOMOD_ACTION_TYPES: Record<string, number> = {
	BLOCK_MESSAGE: 1,
	SEND_ALERT_MESSAGE: 2,
	TIMEOUT: 3,
	BLOCK_MEMBER_INTERACTION: 4,
};

export const DISCORD_AUTOMOD_PRESET_TYPES: Record<string, number> = {
	PROFANITY: 1,
	SEXUAL_CONTENT: 2,
	SLURS: 3,
};

export const listcodes: { name: string; code: string }[] = [
	{ name: "Abkhaz", code: "ab" },
	{ name: "Acehnese", code: "ace" },
	{ name: "Acholi", code: "ach" },
	{ name: "Afar", code: "aa" },
	{ name: "Afrikaans", code: "af" },
	{ name: "Albanian", code: "sq" },
	{ name: "Alur", code: "alz" },
	{ name: "Amharic", code: "am" },
	{ name: "Arabic", code: "ar" },
	{ name: "Armenian", code: "hy" },
	{ name: "Assamese", code: "as" },
	{ name: "Avar", code: "av" },
	{ name: "Awadhi", code: "awa" },
	{ name: "Aymara", code: "ay" },
	{ name: "Azerbaijani", code: "az" },
	{ name: "Balinese", code: "ban" },
	{ name: "Bambara", code: "bm" },
	{ name: "Bashkir", code: "ba" },
	{ name: "Basque", code: "eu" },
	{ name: "Batak Karo", code: "btx" },
	{ name: "Batak Simalungun", code: "bts" },
	{ name: "Batak Toba", code: "bbc" },
	{ name: "Belarusian", code: "be" },
	{ name: "Bengali", code: "bn" },
	{ name: "Bhojpuri", code: "bho" },
	{ name: "Bikol", code: "bik" },
	{ name: "Bosnian", code: "bs" },
	{ name: "Breton", code: "br" },
	{ name: "Bulgarian", code: "bg" },
	{ name: "Buryat", code: "bua" },
	{ name: "Cantonese", code: "yue" },
	{ name: "Catalan", code: "ca" },
	{ name: "Cebuano", code: "ceb" },
	{ name: "Chamorro", code: "ch" },
	{ name: "Chechen", code: "ce" },
	{ name: "Chichewa", code: "ny" },
	{ name: "Chinese (Simplified)", code: "zh-CN" },
	{ name: "Chinese (Traditional)", code: "zh-TW" },
	{ name: "Chuvash", code: "cv" },
	{ name: "Corsican", code: "co" },
	{ name: "Crimean Tatar", code: "crh" },
	{ name: "Croatian", code: "hr" },
	{ name: "Czech", code: "cs" },
	{ name: "Danish", code: "da" },
	{ name: "Dhivehi", code: "dv" },
	{ name: "Dininkka", code: "din" },
	{ name: "Dogri", code: "doi" },
	{ name: "Dombe", code: "dom" },
	{ name: "Dutch", code: "nl" },
	{ name: "Dyula", code: "dyu" },
	{ name: "Dzongkha", code: "dz" },
	{ name: "English", code: "en" },
	{ name: "Esperanto", code: "eo" },
	{ name: "Estonian", code: "et" },
	{ name: "Ewe", code: "ee" },
	{ name: "Faroese", code: "fo" },
	{ name: "Fijian", code: "fj" },
	{ name: "Filipino", code: "fil" },
	{ name: "Finnish", code: "fi" },
	{ name: "French", code: "fr" },
	{ name: "French (Canada)", code: "fr-CA" },
	{ name: "Frisian", code: "fy" },
	{ name: "Friulian", code: "fur" },
	{ name: "Fulani", code: "ff" },
	{ name: "Ga", code: "gaa" },
	{ name: "Galician", code: "gl" },
	{ name: "Georgian", code: "ka" },
	{ name: "German", code: "de" },
	{ name: "Greek", code: "el" },
	{ name: "Guarani", code: "gn" },
	{ name: "Gujarati", code: "gu" },
	{ name: "Haitian Creole", code: "ht" },
	{ name: "Hakha Chin", code: "cnh" },
	{ name: "Hausa", code: "ha" },
	{ name: "Hawaiian", code: "haw" },
	{ name: "Hebrew", code: "he" },
	{ name: "Hindi", code: "hi" },
	{ name: "Hmong", code: "hmn" },
	{ name: "Hungarian", code: "hu" },
	{ name: "Hunsrik", code: "hrx" },
	{ name: "Iban", code: "iba" },
	{ name: "Icelandic", code: "is" },
	{ name: "Igbo", code: "ig" },
	{ name: "Ilocano", code: "ilo" },
	{ name: "Indonesian", code: "id" },
	{ name: "Irish", code: "ga" },
	{ name: "Italian", code: "it" },
	{ name: "Japanese", code: "ja" },
	{ name: "Javanese", code: "jv" },
	{ name: "Jingpo", code: "kac" },
	{ name: "Kalaallisut", code: "kl" },
	{ name: "Kannada", code: "kn" },
	{ name: "Kanuri", code: "kr" },
	{ name: "Kapampangan", code: "pam" },
	{ name: "Kazakh", code: "kk" },
	{ name: "Khasi", code: "kha" },
	{ name: "Khmer", code: "km" },
	{ name: "Kiga", code: "cgg" },
	{ name: "Kikongo", code: "kg" },
	{ name: "Kinyarwanda", code: "rw" },
	{ name: "Kituba", code: "ktu" },
	{ name: "Kokborok", code: "trp" },
	{ name: "Konkani", code: "gom" },
	{ name: "Korean", code: "ko" },
	{ name: "Krio", code: "kri" },
	{ name: "Kurdish (Kurmanji)", code: "ku" },
	{ name: "Kurdish (Sorani)", code: "ckb" },
	{ name: "Kyrgyz", code: "ky" },
	{ name: "Lao", code: "lo" },
	{ name: "Latavian", code: "lv" },
	{ name: "Ligurian", code: "lij" },
	{ name: "Limburgish", code: "li" },
	{ name: "Lingala", code: "ln" },
	{ name: "Lithuanian", code: "lt" },
	{ name: "Lombard", code: "lmo" },
	{ name: "Luganda", code: "lg" },
	{ name: "Luo", code: "luo" },
	{ name: "Luxembourgish", code: "lb" },
	{ name: "Macedonian", code: "mk" },
	{ name: "Madurese", code: "mad" },
	{ name: "Magahi", code: "mag" },
	{ name: "Maithili", code: "mai" },
	{ name: "Makassar", code: "mak" },
	{ name: "Malagasy", code: "mg" },
	{ name: "Malay", code: "ms" },
	{ name: "Malayalam", code: "ml" },
	{ name: "Maltese", code: "mt" },
	{ name: "Mam", code: "mam" },
	{ name: "Manx", code: "gv" },
	{ name: "Maori", code: "mi" },
	{ name: "Marathi", code: "mr" },
	{ name: "Marshallese", code: "mh" },
	{ name: "Marwadi", code: "mwr" },
	{ name: "Mauritian Creole", code: "mfe" },
	{ name: "Meiteilon (Manipuri)", code: "mni-Mtei" },
	{ name: "Minangkabau", code: "min" },
	{ name: "Mizo", code: "lus" },
	{ name: "Mongolian", code: "mn" },
	{ name: "Myanmar (Burmese)", code: "my" },
	{ name: "Nahuatl", code: "nah" },
	{ name: "Ndau", code: "ndc" },
	{ name: "Ndebele (South)", code: "nr" },
	{ name: "Nepalbhasha (Newari)", code: "new" },
	{ name: "Nepali", code: "ne" },
	{ name: "NKo", code: "nko" },
	{ name: "Norwegian", code: "no" },
	{ name: "Nuer", code: "nus" },
	{ name: "Occitan", code: "oc" },
	{ name: "Odia (Oriya)", code: "or" },
	{ name: "Oromo", code: "om" },
	{ name: "Ossetian", code: "os" },
	{ name: "Pangasinan", code: "pag" },
	{ name: "Papiamento", code: "pap" },
	{ name: "Pashto", code: "ps" },
	{ name: "Persian", code: "fa" },
	{ name: "Polish", code: "pl" },
	{ name: "Portuguese (Brazil)", code: "pt-BR" },
	{ name: "Portuguese (Portugal)", code: "pt-PT" },
	{ name: "Punjabi (Gurmukhi)", code: "pa" },
	{ name: "Punjabi (Shahmukhi)", code: "pa-Arab" },
	{ name: "Quechua", code: "qu" },
	{ name: "Qʼeqchiʼ", code: "kek" },
	{ name: "Romani", code: "rom" },
	{ name: "Romanian", code: "ro" },
	{ name: "Rundi", code: "rn" },
	{ name: "Russian", code: "ru" },
	{ name: "Samoan", code: "sm" },
	{ name: "Sango", code: "sg" },
	{ name: "Sanskrit", code: "sa" },
	{ name: "Santali", code: "sat" },
	{ name: "Scots Gaelic", code: "gd" },
	{ name: "Sepedi", code: "nso" },
	{ name: "Serbian", code: "sr" },
	{ name: "Sesotho", code: "st" },
	{ name: "Seychellois Creole", code: "crs" },
	{ name: "Shan", code: "shn" },
	{ name: "Shona", code: "sn" },
	{ name: "Sicilian", code: "scn" },
	{ name: "Silesian", code: "szl" },
	{ name: "Sindhi", code: "sd" },
	{ name: "Sinhala", code: "si" },
	{ name: "Slovak", code: "sk" },
	{ name: "Slovenian", code: "sl" },
	{ name: "Somali", code: "so" },
	{ name: "Spanish", code: "es" },
	{ name: "Sundanese", code: "su" },
	{ name: "Susu", code: "sus" },
	{ name: "Swahili", code: "sw" },
	{ name: "Swati", code: "ss" },
	{ name: "Swedish", code: "sv" },
	{ name: "Tahitian", code: "ty" },
	{ name: "Tajik", code: "tg" },
	{ name: "Tamazight", code: "tzm" },
	{ name: "Tamazight (Tifinagh)", code: "ber-Tfng" },
	{ name: "Tamil", code: "ta" },
	{ name: "Tatar", code: "tt" },
	{ name: "Telugu", code: "te" },
	{ name: "Tetum", code: "tet" },
	{ name: "Thai", code: "th" },
	{ name: "Tibetan", code: "bo" },
	{ name: "Tigrinya", code: "ti" },
	{ name: "Tiv", code: "tiv" },
	{ name: "Tok Pisin", code: "tpi" },
	{ name: "Tongan", code: "to" },
	{ name: "Tsonga", code: "ts" },
	{ name: "Tswana", code: "tn" },
	{ name: "Tulu", code: "tcy" },
	{ name: "Tumbuka", code: "tum" },
	{ name: "Turkish", code: "tr" },
	{ name: "Turkmen", code: "tk" },
	{ name: "Tuvan", code: "tyv" },
	{ name: "Twi", code: "ak" },
	{ name: "Udmurt", code: "udm" },
	{ name: "Ukrainian", code: "uk" },
	{ name: "Urdu", code: "ur" },
	{ name: "Uyghur", code: "ug" },
	{ name: "Uzbek", code: "uz" },
	{ name: "Venda", code: "ve" },
	{ name: "Venetian", code: "vec" },
	{ name: "Vietnamese", code: "vi" },
	{ name: "Waray", code: "war" },
	{ name: "Welsh", code: "cy" },
	{ name: "Wolof", code: "wo" },
	{ name: "Xhosa", code: "xh" },
	{ name: "Yakut", code: "sah" },
	{ name: "Yiddish", code: "yi" },
	{ name: "Yoruba", code: "yo" },
	{ name: "Yucatec Maya", code: "yua" },
	{ name: "Zapotec", code: "zap" },
	{ name: "Zulu", code: "zu" },
];

export const GOOGLE_TTS_REGION: Record<string, string> = {
	en: "US",
	zh: "CN",
	ja: "JP",
	ko: "KR",
	ar: "XA",
	hi: "IN",
	vi: "VN",
	pt: "BR",
	th: "TH",
	no: "NO",
	nb: "NO",
	nn: "NO",
	uk: "UA",
	cs: "CZ",
	da: "DK",
	fi: "FI",
	hu: "HU",
	el: "GR",
	he: "IL",
	ro: "RO",
	sk: "SK",
	sr: "RS",
	hr: "HR",
	bg: "BG",
	ca: "ES",
	eu: "ES",
	gl: "ES",
	sv: "SE",
	pl: "PL",
	ru: "RU",
	tr: "TR",
	id: "ID",
	ms: "MY",
	fa: "IR",
	ur: "PK",
	bn: "IN",
	ta: "IN",
	te: "IN",
	mr: "IN",
	gu: "IN",
	kn: "IN",
	ml: "IN",
	pa: "IN",
	fil: "PH",
	nl: "NL",
	it: "IT",
	es: "ES",
	fr: "FR",
	de: "DE",
};

export const ALLOWED_TAGS = ["{id}", "{title}", "{author}", "{url}", "{source}", "{actualSource}", "{thumbnail}", "{duration}", "{durationMS}", "{isSeekable}", "{isStream}", "{requestedBy}", "{requester}", "{requester.id}", "{requester.username}", "{requester.globalName}", "{requester.tag}", "{requester.avatar}", "{requester.bot}", "{requester.flags}", "{requester.discriminator}", "{requester.banner}", "{requester.accentColor}", "{requester.avatarDecoration}", "{requester.isInVC}", "{playlist}", "{playlist.name}", "{playlist.size}", "{playlist.elapsedTime}", "{playlist.elapsedTime.label}", "{playlist.elapsedTime.value}", "{is247}", "{playing}", "{paused}", "{volume}", "{loop}", "{filters}", "{filters.array}", "{filters.string}", "{queueSize}", "{queue}", "{queue.size}", "{queue.limit_size}", "{queue.elapsedTime}", "{queue.elapsedTime.label}", "{queue.elapsedTime.value}", "{progress}", "{progress.current}", "{progress.current.label}", "{progress.current.value}", "{progress.total}", "{progress.total.label}", "{progress.total.value}", "{platform}", "{nodeId}", "{currentTimestamp}"];
