import fs from "fs";
import path from "path";

const ROUTES_DIR = path.join(import.meta.dir, "routes");

const routeDirs = fs
	.readdirSync(ROUTES_DIR)
	.filter((dir) => fs.statSync(path.join(ROUTES_DIR, dir)).isDirectory());

for (const dir of routeDirs) {
	const dirPath = path.join(ROUTES_DIR, dir);
	const files = fs
		.readdirSync(dirPath)
		.filter((file) => file.endsWith(".ts") && !file.startsWith("index."));

	if (files.length === 0) {
		const content = `// Auto-generated by gen-routes.ts\nexport default [];\n`;
		fs.writeFileSync(path.join(dirPath, "index.ts"), content);
		console.log(`📁 ${dir}/index.ts → (empty)`);
		continue;
	}

	const imports: string[] = [];
	const names: string[] = [];

	for (const file of files) {
		const name = file.replace(".ts", "");

		const safeName = name.replace(/[^a-zA-Z0-9_$]/g, "_");
		imports.push(`import ${safeName} from "./${name}.js";`);
		names.push(safeName);
	}

	const content = [
		`// Auto-generated by gen-routes.ts`,
		...imports,
		``,
		`export default [${names.join(", ")}] as any[];`,
		``,
	].join("\n");

	fs.writeFileSync(path.join(dirPath, "index.ts"), content);
	console.log(`📁 ${dir}/index.ts → ${files.length} routes`);
}

console.log("\n✅ All route indexes generated!");
