// Auto-generated by gen-routes.ts
import connect from "./connect.js";
import disconnect from "./disconnect.js";
import filters from "./filters.js";
import queue from "./queue.js";
import stats from "./stats.js";
import voiceStatus from "./voiceStatus.js";
import controls from "./controls.js";
import radio from "./radio.js";
import messageStatus from "./messageStatus.js";
import play from "./play.js";

export default [connect, disconnect, filters, queue, stats, voiceStatus, controls, radio, messageStatus, play] as any[];
