// Auto-generated by gen-routes.ts
import connect from './connect.js';
import disconnect from './disconnect.js';
import filters from './filters.js';
import play from './play.js';
import queue from './queue.js';
import stats from './stats.js';
import voiceStatus from './voiceStatus.js';
import controls from './controls.js';

export default [connect, disconnect, filters, play, queue, stats, voiceStatus, controls] as any[];
