// Auto-generated by gen-routes.ts
import geminiAmp from './geminiAmp.js';
import translateAmp from './translateAmp.js';
import flux_demo from './flux-demo.js';
import magicstudio from './magicstudio.js';
import discordModifyServer from './discordModifyServer.js';
import discordWebhook from './discordWebhook.js';
import bingImagine from './bingImagine.js';
import meta from './meta.js';
import discordTiktokFeed from './discordTiktokFeed.js';
import discordStream from './discordStream.js';
import grok from './grok.js';
import perplexity from './perplexity.js';
import discordModifyMember from './discordModifyMember.js';
import discordInfoMember from './discordInfoMember.js';
import discordInfoMessages from './discordInfoMessages.js';
import timezone from './timezone.js';

export default [geminiAmp, translateAmp, flux_demo, magicstudio, discordModifyServer, discordWebhook, bingImagine, meta, discordTiktokFeed, discordStream, grok, perplexity, discordModifyMember, discordInfoMember, discordInfoMessages, timezone] as any[];
