// Auto-generated by gen-routes.ts
import geminiAmp from './geminiAmp.js';
import translateAmp from './translateAmp.js';
import meta from './meta.js';
import grok from './grok.js';
import perplexity from './perplexity.js';
import discordInfoMember from './discordInfoMember.js';
import discordInfoMessages from './discordInfoMessages.js';
import timezone from './timezone.js';
import discordModifyMember from './discordModifyMember.js';
import discordModifyServer from './discordModifyServer.js';
import discordStream from './discordStream.js';
import discordTiktokFeed from './discordTiktokFeed.js';
import discordWebhook from './discordWebhook.js';
import magicstudio from './magicstudio.js';
import flux from './flux.js';
import discordListMember from './discordListMember.js';
import ffmpegInterpolate from './ffmpegInterpolate.js';

export default [geminiAmp, translateAmp, meta, grok, perplexity, discordInfoMember, discordInfoMessages, timezone, discordModifyMember, discordModifyServer, discordStream, discordTiktokFeed, discordWebhook, magicstudio, flux, discordListMember, ffmpegInterpolate] as any[];
