// Auto-generated by gen-routes.ts
import deezer from "./deezer.js";
import youtube from "./youtube.js";
import tidal from "./tidal.js";
import spotify from "./spotify.js";
import shazam from "./shazam.js";

export default [deezer, youtube, tidal, spotify, shazam] as any[];
