// Auto-generated by gen-routes.ts
import deezer from "./deezer.js";
import kugou from "./kugou.js";
import shazam from "./shazam.js";
import spotify from "./spotify.js";
import tidal from "./tidal.js";
import youtube from "./youtube.js";

export default [deezer, kugou, shazam, spotify, tidal, youtube] as any[];
