// Auto-generated by gen-routes.ts
import facebookPhoto from "./facebookPhoto.js";
import facebookVideo from "./facebookVideo.js";
import instagramPhoto from "./instagramPhoto.js";
import instagramVideo from "./instagramVideo.js";
import threadsPhoto from "./threadsPhoto.js";
import threadsVideo from "./threadsVideo.js";
import tiktokPhoto from "./tiktokPhoto.js";
import tiktokVideo from "./tiktokVideo.js";
import twitterPhoto from "./twitterPhoto.js";
import twitterVideo from "./twitterVideo.js";

export default [facebookPhoto, facebookVideo, instagramPhoto, instagramVideo, threadsPhoto, threadsVideo, tiktokPhoto, tiktokVideo, twitterPhoto, twitterVideo] as any[];
