// Auto-generated by gen-routes.ts
import infoYoutube from './infoYoutube.js';
import infoSoundcloud from './infoSoundcloud.js';
import infoSpotify from './infoSpotify.js';
import infoITunes from './infoITunes.js';
import infoTwitterUser from './infoTwitterUser.js';
import infoTwitterTweet from './infoTwitterTweet.js';
import redditSubreddit from './redditSubreddit.js';
import infoInstagramUser from './infoInstagramUser.js';
import infoThreadUser from './infoThreadUser.js';
import infoGiphy from './infoGiphy.js';
import infoTenor from './infoTenor.js';
import googleWeather from './googleWeather.js';
import infoKlipy from './infoKlipy.js';
import infoPinterest from './infoPinterest.js';
import infoTiktokVideo from './infoTiktokVideo.js';
import redditPost from './redditPost.js';

export default [infoYoutube, infoSoundcloud, infoSpotify, infoITunes, infoTwitterUser, infoTwitterTweet, redditSubreddit, infoInstagramUser, infoThreadUser, infoGiphy, infoTenor, googleWeather, infoKlipy, infoPinterest, infoTiktokVideo, redditPost] as any[];
