// Auto-generated by gen-routes.ts
import googleWeather from "./googleWeather.js";
import infoGiphy from "./infoGiphy.js";
import infoITunes from "./infoITunes.js";
import infoKlipy from "./infoKlipy.js";
import infoPinterest from "./infoPinterest.js";
import infoSoundcloud from "./infoSoundcloud.js";
import infoSpotify from "./infoSpotify.js";
import infoTenor from "./infoTenor.js";
import infoTiktokVideo from "./infoTiktokVideo.js";
import infoTwitterTweet from "./infoTwitterTweet.js";
import infoYoutube from "./infoYoutube.js";
import redditPost from "./redditPost.js";
import redditSubreddit from "./redditSubreddit.js";

export default [googleWeather, infoGiphy, infoITunes, infoKlipy, infoPinterest, infoSoundcloud, infoSpotify, infoTenor, infoTiktokVideo, infoTwitterTweet, infoYoutube, redditPost, redditSubreddit] as any[];
